import "./globals.css";
import React from "react";
import LayoutWrapper from "@/components/layout-wrapper/layout-wrapper";

export const metadata = {
    title: "Chinhtkt's gaming hub",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" className="h-full">
        <body className="h-full">
            <LayoutWrapper>
                {children}
            </LayoutWrapper>
        </body>
        </html>
    );
}

